export const CATEGORIES = [
  {
    id: 1,
    name: "iPhones",
    slug: "iphones",
    image: "/assets/categories/iphone.png",
  },
  {
    id: 2,
    name: "iPads",
    slug: "ipads",
    image: "/assets/categories/ipad.jpeg",
  },
  {
    id: 3,
    name: "macBooks",
    slug: "macbooks",
    image: "/assets/categories/macbooks.jpeg",
  },
  {
    id: 4,
    name: "accessories",
    slug: "accessories",
    image: "/assets/categories/accessories.png",
  },
  {
    id: 5,
    name: "androids",
    slug: "androids",
    image: "/assets/categories/android.jpeg",
  },
  {
    id: 6,
    name: "smartwatches",
    slug: "smartwatches",
    image: "/assets/categories/smartwatch.png",
  },
  {
    id: 7,
    name: "headphones",
    slug: "headphones",
    image: "/assets/categories/headphones.jpeg",
  },
  {
    id: 8,
    name: "speakers",
    slug: "speakers",
    image: "/assets/categories/speakers.jpeg",
  },
  {
    id: 9,
    name: "desktops",
    slug: "desktops",
    image: "/assets/categories/desktop.jpeg",
  },
  {
    id: 10,
    name: "cables",
    slug: "cables",
    image: "/assets/categories/cables.jpeg",
  },
  {
    id: 11,
    name: "keyboards",
    slug: "keyboards",
    image: "/assets/categories/keyboard.jpeg",
  },
  {
    id: 12,
    name: "Others",
    slug: "others",
    image: "/assets/categories/others.jpeg",
  },
];

export const PRODUCTS_PAGE = {
  title: "iPhones",
  products: [
    {
      id: 1,
      category: "iphones",
      name: "iPhone 13 Pro",
      image: "/assets/categories/iphone.png",
      cost_price: 1099,
      selling_price: 999,
      rating: 4.3,
      number_of_reviews: 100,
      description: "The iPhone 13 Pro is the best iPhone to date. It has the best camera, the best battery life, and the best performance of any iPhone. It is also the most expensive iPhone to date.",
      stock: 100,
      colors: [
        {
          name: "Black",
          code: "#000000",
          image: "/assets/categories/iphone.png",
        },
        {
          name: "White",
          code: "#ffffff",
          image: "/assets/categories/iphone.png",
        },
        {
          name: "Red",
          code: "#ff0000",
          image: "/assets/categories/iphone.png",
        },
      ],
    },
    {
      id: 2,
      category: "iphones",
      name: "iPhone 13",
      image: "/assets/categories/iphone.png",
      cost_price: 899,
      selling_price: 899,
      rating: 4.3,
      number_of_reviews: 100,
      description: "The iPhone 13 is the best iPhone to date. It has the best camera, the best battery life, and the best performance of any iPhone. It is also the most expensive iPhone to date.",
      stock: 100,
      colors: [
        {
          name: "Black",
          code: "#000000",
          image: "/assets/categories/iphone.png",
        },
        {
          name: "White",
          code: "#ffffff",
          image: "/assets/categories/iphone.png",
        },
        {
          name: "Red",
          code: "#ff0000",
          image: "/assets/categories/iphone.png",
        },
      ],
    },
    {
      id: 3,
      category: "iphones",
      name: "iPhone 12 Pro",
      image: "/assets/categories/iphone.png",
      cost_price: 799,
      selling_price: 699,
      rating: 4.8,
      number_of_reviews: 100,
      description: "The iPhone 12 Pro is the best iPhone to date. It has the best camera, the best battery life, and the best performance of any iPhone. It is also the most expensive iPhone to date.",
      stock: 100,
      colors: [
        {
          name: "Black",
          code: "#000000",
          image: "/assets/categories/iphone.png",
        },
        {
          name: "White",
          code: "#ffffff",
          image: "/assets/categories/iphone.png",
        },
        {
          name: "Red",
          code: "#ff0000",
          image: "/assets/categories/iphone.png",
        },
      ],
    },
    {
      id: 4,
      category: "iphones",
      name: "iPhone 12",
      image: "/assets/categories/iphone.png",
      cost_price: 699,
      selling_price: 699,
      rating: 3.7,
      number_of_reviews: 100,
      description: "The iPhone 12 is the best iPhone to date. It has the best camera, the best battery life, and the best performance of any iPhone. It is also the most expensive iPhone to date.",
      stock: 100,
      colors: [
        {
          name: "Black",
          code: "#000000",
          image: "/assets/categories/iphone.png",
        },
        {
          name: "White",
          code: "#ffffff",
          image: "/assets/categories/iphone.png",
        },
        {
          name: "Red",
          code: "#ff0000",
          image: "/assets/categories/iphone.png",
        },
      ],
    },
    {
      id: 5,
      category: "iphones",
      name: "iPhone 11 Pro",
      image: "/assets/categories/iphone.png",
      cost_price: 599,
      selling_price: 599,
      rating: 4.3,
      number_of_reviews: 100,
      description: "The iPhone 11 Pro is the best iPhone to date. It has the best camera, the best battery life, and the best performance of any iPhone. It is also the most expensive iPhone to date.",
      stock: 100,
      colors: [
        {
          name: "Black",
          code: "#000000",
          image: "/assets/categories/iphone.png",
        },
        {
          name: "White",
          code: "#ffffff",
          image: "/assets/categories/iphone.png",
        },
        {
          name: "Red",
          code: "#ff0000",
          image: "/assets/categories/iphone.png",
        },
      ],
    },
  ],
};
